[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PRIVATE_TARGET = "server"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# API functions
[functions]
  directory = "netlify/functions"

# Environment variables (set in Netlify dashboard)
# MONGODB_URI=your_mongodb_connection
# NEXTAUTH_SECRET=your_secret
# NEXTAUTH_URL=https://yoursite.netlify.app
