version: 2
build:
  commands:
    - npm ci
    - npm run build
  watch: ["package.json", "package-lock.json"]
deploy:
  startCommand: npm start
  healthcheckPath: "/api/health"
  healthcheckTimeout: 300
  restartPolicyType: "always"
environments:
  production:
    variables:
      NODE_ENV: production
      PORT: ${{ PORT }}
    secrets:
      - MONGODB_URI
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
